// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQ9uvVL6nhNnYobMOAHdfLM1Pgkwjt-g',
    appId: '1:687197364566:web:38dcb798683f28dbf876f7',
    messagingSenderId: '687197364566',
    projectId: 'whatscooking-3d284',
    authDomain: 'whatscooking-3d284.firebaseapp.com',
    storageBucket: 'whatscooking-3d284.appspot.com',
    measurementId: 'G-NPHCP5TN1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIR9nnfEffXgXoJKANauzrvyDB7dElS8Q',
    appId: '1:687197364566:android:974759338da2bfe1f876f7',
    messagingSenderId: '687197364566',
    projectId: 'whatscooking-3d284',
    storageBucket: 'whatscooking-3d284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3_YaP3IvIMQKUAbB5TtBwR2InCfOINs',
    appId: '1:687197364566:ios:7a0d78e6185ddb28f876f7',
    messagingSenderId: '687197364566',
    projectId: 'whatscooking-3d284',
    storageBucket: 'whatscooking-3d284.appspot.com',
    iosClientId: '687197364566-mma0d8r8880opj02kurcnoma81jsvbd2.apps.googleusercontent.com',
    iosBundleId: 'com.zubaidalabs.whatscooking',
  );
}
